pipeline {
    agent any
       parameters {
        string(name: 's3_bucket_name', description: 'Name of s3 bucket you want to create')

        choice(name: 'region', choices: ['us-east-1', 'us-east-2'], description: 'select region to create the bucket')

      
    }

    stages {
        stage('Create S3 bucket') {
            steps {
                script{
                   sh "aws s3api create-bucket --bucket ${params.s3_bucket_name} --region ${params.region}"
                }
                

                
               
            }
            
        }
        
        stage('list S3 bucket') {
            steps {
                script{
                echo 'list of the s3 buckets in the region'
                
                   sh " aws s3 ls"
                }
                
                
            }
        }
        stage('Delete s3 bucket') {
            steps {
                script{
                echo 'Delete the s3 bucket'
                sleep 60
                
                 sh "aws s3api delete-bucket --bucket ${params.s3_bucket_name} --region ${params.region}"
                
                
                echo "bucket ${params.s3_bucket_name} deleted successfully"
                }
            }
        }
    }
}